name: decent_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  stroke_text: ^1.0.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  awesome_video_player: ^1.0.5
  chewie: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
